name: Spectral Linting
author: Vincenzo Chianese
description: Lint your files with Spectral
inputs:
  file_glob:
    required: true
    description: The file path to lint with Spectral
    default: '*.oas.{json,yml,yaml}'
  spectral_ruleset:
    required: true
    description: Ruleset file to load in Spectral
    default: 'spectral:oas'
  repo_token:
    required: true
    description: |
      The GitHub App installation access token.

      [Learn more about `GITHUB_TOKEN`](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret)
    default: ${{ github.token }}
runs:
  using: docker
  image: Dockerfile
branding:
  icon: code
  color: yellow
