on: push
name: Build Pipeline
jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Spectral checks
        uses: ./
        with:
          file_path: test.oas.json
